# vim ft=yaml
language: python

git:
  # we use submodules to be managed with datalad
  submodules: false

python:
  #  - 2.7
  - 3.6

cache:
  - apt

env:
  global:
    # will be used in the matrix, where neither other variable is used
    - COVERAGE=coverage

before_install:
  # The ultimate one-liner setup for NeuroDebian repository
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo eatmydata apt-get install --no-install-recommends git-annex-standalone aria2 git-remote-gcrypt lsof gnupg nocache

install:
  # Install standalone build of git-annex for the recent enough version
  - travis_retry sudo eatmydata apt-get install pandoc
  - cd ..; pip install -q codecov; cd -
  - pip install -r requirements-devel.txt

script:
  # Report WTF information using system wide installed version
  - datalad wtf
  # Verify that setup.py build doesn't puke
  - python setup.py build
  # Test installation system-wide
  - pip install -e .
  # Run tests
  - PATH=$PWD/tools/coverage-bin:$PATH
    python -m pytest -s -v --cov=remodnav --cov-report=term-missing .

after_success:
  - coverage combine -a /tmp/.coverage-entrypoints-*
  - codecov
